Accept 8.0 Bidi files and reject CCX files
kaitai-io/coreldraw_cdr.ksy pull request #3
Opened 2023-06-28 11:39 UTC by zachwolfe

2023-07-04 14:00 UTC, generalmimon requested changes
Sorry for the delay - I'll try to be faster next time.

2023-07-04 14:00 UTC, generalmimon commented on coreldraw_cdr.ksy
> +          expr: 'c != 88'
I'd prefer to use the hexadecimal notation:

```suggestion
          # Note that this rule also makes the string "cdrX" invalid. However, given that the CDR
          # Bidi format is a variant of the 8.0 version, plugging 0x58 into the expression in the
          # `version` instance below reveals that it would fall well outside of the acceptable
          # range anyway.
          expr: 'c != 0x58'
```

And I'm not sure I understand this (I'd rather omit this part completely):

> However, given that the CDR Bidi format is a variant of the 8.0 version, plugging 0x58 into the expression in the `version` instance below reveals that it would fall well outside of the acceptable range anyway.

What exactly do you mean by the "acceptable range" in this context? `CDRP` is the latest CDR form type I've seen, used for version 2400. The ASCII code of the `P` character is `0x50`, so it's true that we're not at `0x58` (for `X`) yet, but it's not that far - so to me, it's very well within a somewhat conceivable range.

2023-07-04 14:00 UTC, generalmimon commented on coreldraw_cdr.ksy
> +            ? 801 :
This is not correct - only `cdr8` can be considered to be the CDR 8.0 Bidi version. Checking just that the first 3 characters of the form type are lowercase `cdr` is not enough.

CorelDRAW 6 includes four CDR sample files: `DRAW/SAMPLES/{6EFFECTS.CDR,PGLAYOUT.CDR,WISHLIST.CDR}` and `DRAW/TUTORIAL/LAYOUT.CDR`. `6EFFECTS.CDR` and `WISHLIST.CDR` use `cdr6` as form type, the other two files use `CDR6` as usual. But they all have the same version (600) in the `vrsn` chunk (unlike the CDR 8.0 vs. CDR 8.0 Bidi versions, where CDR 8.0 files use 800 and CDR 8.0 Bidi files use 801):

```console
$ for f in DRAW_SAMPLES/{6EFFECTS,WISHLIST}.CDR DRAW_SAMPLES/PGLAYOUT.CDR DRAW_TUTORIAL/LAYOUT.CDR; do echo "$f"; xxd -l 22 "$f"; done
DRAW_SAMPLES/6EFFECTS.CDR
00000000: 5249 4646 c4fa 0800 6364 7236 7672 736e  RIFF....cdr6vrsn
00000010: 0200 0000 5802                           ....X.
DRAW_SAMPLES/WISHLIST.CDR
00000000: 5249 4646 0aea 0200 6364 7236 7672 736e  RIFF....cdr6vrsn
00000010: 0200 0000 5802                           ....X.
DRAW_SAMPLES/PGLAYOUT.CDR
00000000: 5249 4646 faa8 0900 4344 5236 7672 736e  RIFF....CDR6vrsn
00000010: 0200 0000 5802                           ....X.
DRAW_TUTORIAL/LAYOUT.CDR
00000000: 5249 4646 142f 0500 4344 5236 7672 736e  RIFF./..CDR6vrsn
00000010: 0200 0000 5802                           ....X.
```

The CDR files with `cdr6` form type are loaded normally in CorelDRAW, but for example loading `6EFFECTS.CDR` and saving it to a new .cdr file with CorelDRAW 6 will change the form type to `CDR6` (the file structure remains the same, except for `fill_id`/`outl_id`/other IDs being renumbered, but that's normal). So `CDR6` and `cdr6` seem to be interchangeable - you can take any CDR 6 file and change the letter case of the form type, and it will keep working in CorelDRAW the same. This seems to be specific to CDR 6, though (it doesn't apply to other versions of CDR, as far as I know).

I don't think it's possible to generate a .cdr file with the `cdr6` from CorelDRAW - I suppose it only produces `CDR6` files. So this anomaly might only apply to the sample files that came with CorelDRAW 6, but still.

2023-07-05 02:54 UTC, zachwolfe commented on coreldraw_cdr.ksy
> +            ? 801 :
Good catch.

2023-07-05 02:54 UTC, zachwolfe commented on coreldraw_cdr.ksy
> +          expr: 'c != 88'
By "acceptable range" I meant 800-899, the set of versions* which could in theory correspond to versions of the CDR 8 Bidi format. I was just trying to say that even though the purpose of the condition was to reject `CDRX`, not `cdrX`, the latter being rejected as well should not be a problem. But I can remove that paragraph if you don't think it's necessary.

*Of course, in practice there was only one CDR 8.0 Bidi version as far as I know, and the `version` instance can only produce multiples of `100`, with the new exception of `801`.

2023-07-05 03:08 UTC, zachwolfe commented
@generalmimon No problem re: the delay. I think the feedback should all be resolved now.

2023-07-05 06:33 UTC, generalmimon approved these changes
Thanks!

2023-07-05 06:34 UTC, merged